language: node_js
node_js:
  - '12'
before_install: cd example && npm install && cd ..
before_deploy: npm run build
deploy:
  provider: npm
  email: 709192822@qq.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
  tag: latest